library(tidyverse)
library(ape)
library(ade4)
library(adegenet)
library(phangorn)
library(Biostrings)
library(DECIPHER)

bingo <- fasta2DNAbin(file = "pmskrd.fasta", quiet = FALSE)
DM <- dist.dna(bingo, model = "TN93", gamma = 0.54)
temp <- as.data.frame(as.matrix(DM))
tre <- ape::nj(DM)
class(tre)
tree <- bionj(DM)
class(tree)
tre <- ape::ladderize(tre)
tree <- ape::ladderize(tree)
plot(tre, cex = 0.7)
dev.off()
plot(tree, cex = 0.7)
dev.off()
tre.cluster <- hclust(DM, method = "average", members = NULL)
plot(tre.cluster, cex = 0.7, hang = -1)
x <- as.vector(DM)
y <- as.vector(as.dist(cophenetic(tree)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is NJ appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
tre2 <- as.phylo(hclust(DM, method = "average"))
y <- as.vector(as.dist(cophenetic(tre2)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is UPGMA appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
tre3 <- as.phylo(hclust(DM, method = "complete"))
y <- as.vector(as.dist(cophenetic(tre3)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is 'complete' appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
tre4 <- as.phylo(hclust(DM, method = "ward.D"))
y <- as.vector(as.dist(cophenetic(tre4)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is 'ward.D' appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
tre5 <- as.phylo(hclust(DM, method = "ward.D2"))
y <- as.vector(as.dist(cophenetic(tre5)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is 'ward.D2' appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
tre6 <- as.phylo(hclust(DM, method = "single"))
y <- as.vector(as.dist(cophenetic(tre6)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is 'single' appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
y <- as.vector(as.dist(cophenetic(tree)))
plot(x, y, xlab = "og pairwise distances", ylab = "pairwise distances on the tree", main = "Is 'NJ2' appropriate?", pch = 20, col = transp("black", 0.1), cex = 3)
abline(lm(y~x), col = "red")
cor(x, y)^2
myBoots <- boot.phylo(tre, bingo, function(e) root(njs(dist.dna(e, model = "TN93")), 1))
myBStr <- boot.phylo(tree, bingo, function(e) root(bionjs(dist.dna(e, model = "TN93")), 1))
plot(tre, show.tip = TRUE, edge.width = 1)
nodelabels(myBoots, cex = 0.3)

dna2 <- as.phyDat(bingo)
tre.ini <- nj(dist.dna(bingo, model = "TN93"))
pml(tre.ini, dna2, k = 4)
table(as.character(dna2))
na.posi <- which(apply(as.character(bingo), 2, function(e) any(!e %in% c("a", "t", "g", "c"))))
temp <- apply(as.character(bingo), 2, function(e) sum(!e %in% c("a", "t", "g", "c")))
plot(temp, type = "l", col = "blue", xlab = "Position in HA segment", ylab = "Number of NAs")
dna3 <- bingo[, -na.posi]
table(as.character(dna3))
dna4 <- as.phyDat(dna3)
tre.ini <- nj(dist.dna(dna3, model = "TN93"))
fit.ini <- pml(tre.ini, dna4, k = 4)
fit <- optim.pml(fit.ini, optNni = TRUE, optBf = TRUE, optQ = TRUE, optGamma = TRUE)
anova(fit.ini, fit)
AIC(fit.ini)
AIC(fit)
tre4 <- root(fit$tree, 1)
tre4 <- ladderize(tre4)
plot(tre4, show.tip = TRUE)
axisPhylo()
