---
title: "ML_Heatmap"
output: html_document
---

## Paquetes
```{r, echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
library(tidyverse) #Generalmente uso paquetes del mundo tidy para facilitar el orden y flujo de trabajo
library(viridis) #Paletas de colores para gráficos
library(Biostrings) #
library(DECIPHER) #
library(dendextend) #
library(heatmaply) #Paquete para crear heatmaps interactivos
library(htmlwidgets) #Paquete para guardar objetos y graficos interactivos
```

## Creación FASTA
Dejaremos como nombre solo "ASV_", si quieres puedes editar o dejar el nombre en el formato que más te acomode
```{r cars, echo=FALSE, message=TRUE, warning=TRUE, include=FALSE}
seqtab.nochim <- read.csv2("https://raw.githubusercontent.com/cmlglvz/datasets/master/Data/eAnalisis/ShaASVs.csv", header = TRUE, skip = 0, sep = ";", dec = ".", fill = TRUE)
rownames(seqtab.nochim) <- seqtab.nochim[, 1]
seqtab.nochim <- seqtab.nochim[, -1]

#El proceso es el mismo desde el final del pipeline de DADA2
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode = "character")
for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep = "_")
}
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "exASVs.fasta")
```

## Alineamiento y Máxima Verosimilitud
Ojo que esta etapa puede tomar mucho tiempo de acuerdo a la cantidad de secuencias con las que trabajaras, así que con paciencia!
```{r, echo=FALSE, message=TRUE, warning=TRUE, include=FALSE}
Ali <- "exASVs.fasta"
dbConn <- dbConnect(SQLite(), ":memory:")
Seqs2DB(Ali, type = "FASTA", dbFile = dbConn, "")

# identify the sequences by their species
x <- dbGetQuery(dbConn, "select description from Seqs")$description
Add2DB(myData = data.frame(identifier = x, stringsAsFactors = FALSE), dbConn)

# form a consensus for each species
cons <- IdConsensus(dbConn, threshold = 0.3, minInformation = 0.1)

# calculate a maximum likelihood tree
d <- DistanceMatrix(cons, correction = "Jukes-Cantor", processors = NULL, verbose = TRUE)
dend <- IdClusters(d, 
                   method = "ML", 
                   showPlot = TRUE, 
                   type = "dendrogram", 
                   myXStringSet = cons, 
                   processors = NULL, 
                   verbose = TRUE)

hclust <- as.hclust(dend)
plot(hclust, hang = -1, cex = 0.7)
devolve <- as.dendrogram(hclust)
plot(devolve)

dbDisconnect(dbConn)

c.dend <- devolve %>% set("branches_lwd", 0.3) %>% ladderize()
```

## Heatmap interactivo
```{r}
v.heatmap <- heatmaply(normalize(seqtab.nochim), 
                       Colv = c.dend, 
                       Rowv = NA, 
                       main = "Titulo",
                       margins = c(50, 50, 70, 0),
                       grid_gap = 1, 
                       width = 1920,
                       height = 1080, 
                       subplot_heights = c(0.35, 0.65), 
                       color = viridis(n = 256, 
                                       alpha = 1, 
                                       begin = 0, 
                                       end = 1, 
                                       option = "viridis")
)
saveWidget(v.heatmap, file = "heatmap_uno.html")

h.heatmap <- heatmaply(normalize(seqtab.nochim),
                       Colv = c.dend, 
                       Rowv = NA, 
                       main = "titulo", 
                       margins = c(50, 50, 70, 0), 
                       grid_gap = 1, 
                       grid_color = "#DEE2E6", 
                       width = 1920, 
                       height = 1080, 
                       subplot_heights = c(0.48, 0.52), 
                       color = heat.colors(n = 256, 
                                           alpha = 1, 
                                           rev = TRUE)
)
saveWidget(h.heatmap, file = "heatmap_dos.html")
```

## END
